name: App tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  prep-environment:
    name: Prepare enviroment
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
    - name: Install dependencies
      run: |
        cd CarRental.Frontend
        npm install
        npx playwright install --with-deps
        cd ../CarRental.Mobile
        npm install
        cd ../CarRental.Backend
        dotnet restore     
  build:
      name: Build projects
      runs-on: self-hosted
      needs: [prep-environment]
      steps:
      - name: Build projects
        run: |
          cd CarRental.Frontend
          npm run build
          cd ../CarRental.Backend
          dotnet build --configuration Release
  test:
    name: Test projects
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Unit Tests
        run: |
          cd CarRental.Tests
          dotnet test --configuration Release
          cd ../CarRental.Frontend
          npm test
          cd ../CarRental.Mobile
          npm test
  e2e:
    name: E2E tests
    runs-on: self-hosted
    needs: [test]  
    steps:
      - name: Deploy projects
        run: |
          cd CarRental.Frontend
          npm start &
      - name: E2E tests
        run: |
          cd CarRental.Backend
          dotnet run &
          cd ../CarRental.Frontend
          npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  save-artifacts:
      name: Save artifacts
      runs-on: self-hosted
      needs: [e2e]
      steps:
      - uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: CarRental.Frontend/build/
      - uses: actions/upload-artifact@v3
        with:
          name: backend
          path: CarRental.Backend/bin/Release/