name: .NET Core API tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test
