name: App tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prep-environment:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
      name: Checkout repository
      
    - name: Install dependencies
      run: |
        cd CarRental.Frontend
        npm install
        cd ../CarRental.Mobile
        npm install
        cd ../CarRental.Backend
        dotnet restore
        
    - name: Build projects
      run: |
        cd CarRental.Frontend
        npm run build
        cd ../CarRental.Mobile
        npm run build
        cd ../CarRental.Backend
        dotnet build --configuration Release
        
    - name: Test projects
      run: |
        cd ../CarRental.Backend
        dotnet test --configuration Release
        cd CarRental.Frontend
        npm test
        cd ../CarRental.Mobile
        npm test
